# Part - 1

In [ ]:
import pandas as pd

In [ ]:
x= pd.Series([1,5,10,4,5])

In [ ]:
type(x)

pandas.core.series.Series

In [ ]:
x.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
x.ndim

1

In [ ]:
x.size

5

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

1

In [ ]:
x.values

array([ 1,  5, 10,  4,  5])

In [ ]:
type(x.values)

numpy.ndarray

Veri Okuma

In [ ]:
df = pd.read_csv("username.csv", sep=";")
# read_excel
# read_table
# read_sql
# read_json

FileNotFoundError: [Errno 2] No such file or directory: 'username.csv'

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df
# head, tail

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.shape

(891, 15)

In [ ]:
df.describe

<bound method NDFrame.describe of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df.describe().T

          count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [ ]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
df.isnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
df.isnull().values.any()

True

In [ ]:
df.isnull().values.sum()

869

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df["sex"].head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [ ]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
type(df["sex"].value_counts())

pandas.core.series.Series

# Part - 2

In [1]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")

In [2]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [4]:
df[0:13]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
delete_indexes = [0,2,4,6]
df.drop(delete_indexes,axis = 0).head() #inplace=True

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False

In [6]:
df.index = df.age
df.drop("age", axis=1,inplace=True)
df.head()
# index satirlarini yani soldaki
# 1234567 diye giden sayilar yerine yas kolonunu kullandik

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
df.age = df.index
# tekrar ageyi ekledik

# indexide resetlemek istersek
df.reset_index(inplace=True)
df.head()

<ipython-input-7-5885001a41c5>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.age = df.index

,age,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
"age" in df

True

In [9]:
print(df["age"].head())
print(type(df["age"].head()))
# pandas serisi olarak geldi

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64
<class 'pandas.core.series.Series'>

In [10]:
print(df[["age"]].head())
print(type(df[["age"]].head()))
# pandas dataframe olarak geldi

    age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0
<class 'pandas.core.frame.DataFrame'>

In [11]:
# birden fazla col secimi
#1
df[["age", "alive"]]
#2
col_names = ["age", "alive"]
df[col_names]

      age alive
0    22.0    no
1    38.0   yes
2    26.0   yes
3    35.0   yes
4    35.0    no
..    ...   ...
886  27.0    no
887  19.0   yes
888   NaN    no
889  26.0   yes
890  32.0    no

[891 rows x 2 columns]

In [12]:
df["age_new"] = df["age"] ** 2
df.head()
# age sutunun karesini alir ve yeni colon olusturur

,age,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_new
0,22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0
1,38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0
2,26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0
3,35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0
4,35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0

In [13]:
# kolonlardaki belirli str ifadelerini secme

print(df.loc[:, df.columns.str.contains("age")].head())
# kolon isimlerinde age ifadesini barindiranlari secti
print(df.loc[:, ~df.columns.str.contains("age")].head())
# ~ tilda isareti onun disindakilerini sec anlamina getirdi

    age  age_new
0  22.0    484.0
1  38.0   1444.0
2  26.0    676.0
3  35.0   1225.0
4  35.0   1225.0
   survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man
1         1       1  female      1      0  71.2833        C  First  woman
2         1       3  female      0      0   7.9250        S  Third  woman
3         1       1  female      1      0  53.1000        S  First  woman
4         0       3    male      0      0   8.0500        S  Third    man

   adult_male deck  embark_town alive  alone
0        True  NaN  Southampton    no  False
1       False    C    Cherbourg   yes  False
2       False  NaN  Southampton   yes   True
3       False    C  Southampton   yes  False
4        True  NaN  Southampton    no   True

In [14]:
# loc & iloc

# loc label based selection Satır ve sütun isimlerini kullanarak veri seçimi yaparsınız. İndeksler ve sütun isimleri ile çalışır.
# iloc integer based selection Satır ve sütunların pozisyon numaralarını kullanarak veri seçimi yaparsınız. Yani, indekslerin sıralı numaraları ile çalışır.

print(df.loc[0:3]) # 0dan 3e kadar olan idexleri getirir
print(df.iloc[0,3]) # 0.satir 3.sutundaki elemani getirir

print(df.iloc[0:3, 0:1])
print(df.loc[0:3, "age"])

col_names = ["age", "embarked", "alive"]
print(df.loc[0:3, col_names])

    age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third
1  38.0         1       1  female      1      0  71.2833        C  First
2  26.0         1       3  female      0      0   7.9250        S  Third
3  35.0         1       1  female      1      0  53.1000        S  First

     who  adult_male deck  embark_town alive  alone  age_new
0    man        True  NaN  Southampton    no  False    484.0
1  woman       False    C    Cherbourg   yes  False   1444.0
2  woman       False  NaN  Southampton   yes   True    676.0
3  woman       False    C  Southampton   yes  False   1225.0
male
    age
0  22.0
1  38.0
2  26.0
0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64
    age embarked alive
0  22.0        S    no
1  38.0        C   yes
2  26.0        S   yes
3  35.0        S   yes

In [15]:
# kosullu islemler

#value_counts frekanslarini verir
print(df['embark_town'].value_counts())

print(df[df["age"] > 50].head())
print(df[df["age"] > 50]["age"].count())
#degisken ismi girilecekse loc
print(df.loc[(df["age"] > 50) & (df["sex"] == "male"), ["age","class"]].head())

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64
     age  survived  pclass     sex  sibsp  parch     fare embarked   class  \
6   54.0         0       1    male      0      0  51.8625        S   First
11  58.0         1       1  female      0      0  26.5500        S   First
15  55.0         1       2  female      0      0  16.0000        S  Second
33  66.0         0       2    male      0      0  10.5000        S  Second
54  65.0         0       1    male      0      1  61.9792        C   First

      who  adult_male deck  embark_town alive  alone  age_new
6     man        True    E  Southampton    no   True   2916.0
11  woman       False    C  Southampton   yes   True   3364.0
15  woman       False  NaN  Southampton   yes   True   3025.0
33    man        True  NaN  Southampton    no   True   4356.0
54    man        True    B    Cherbourg    no  False   4225.0
64
     age   class
6   54.0   First
33  66.0  Second
54  65.0   First
94  59.0   Third
96  71.0   First

In [16]:
# Toplulastirma ve Gruplama

# toplulastirma ozet istatistik veren fonksiyonlardir (first last mean median min max std count)
# gruplastirma agg ile yapilandir

print(df["age"].mean())


print(df.groupby("sex")["age"].mean())
# bu sekilde degilde

print(df.groupby("sex").agg({"age": ["mean","sum","min","max","count"]}))
# bu sekilde uygula cunku hem mean hem sum ne istersen ekleyebilirsin

print(df.groupby("sex").agg({"age": ["mean","sum","min","max","count"],
                             "survived": "mean"}))


print(df.groupby(["class","embark_town"]).agg({"age":"mean",
                             "survived":"mean"}))

print(df.groupby(["sex", "class"]).agg({
    "age":"mean",
    "survived":"mean",
    "sex":"count"
}))

29.69911764705882
sex
female    27.915709
male      30.726645
Name: age, dtype: float64
              age
             mean       sum   min   max count
sex
female  27.915709   7286.00  0.75  63.0   261
male    30.726645  13919.17  0.42  80.0   453
              age                              survived
             mean       sum   min   max count      mean
sex
female  27.915709   7286.00  0.75  63.0   261  0.742038
male    30.726645  13919.17  0.42  80.0   453  0.188908
                          age  survived
class  embark_town
First  Cherbourg    38.027027  0.694118
       Queenstown   38.500000  0.500000
       Southampton  38.152037  0.582677
Second Cherbourg    22.766667  0.529412
       Queenstown   43.500000  0.666667
       Southampton  30.386731  0.463415
Third  Cherbourg    20.741951  0.378788
       Queenstown   25.937500  0.375000
       Southampton  25.696552  0.189802
                     age  survived  sex
sex    class
female First   34.611765  0.968085   94
       Second  28.722973  0.921053   76
       Third   21.750000  0.500000  144
male   First   41.281386  0.368852  122
       Second  30.740707  0.157407  108
       Third   26.507589  0.135447  347

<ipython-input-16-e7056943ab62>:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(["class","embark_town"]).agg({"age":"mean",
<ipython-input-16-e7056943ab62>:22: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(["sex", "class"]).agg({

In [22]:
# Pivot Table

print(df.pivot_table("survived", "sex", "embarked"))
print("``````````````````````````````")
print(df.pivot_table("survived", "sex", ["embarked", "class"]))
print("``````````````````````````````")
print(df.pivot_table("survived", "sex", ["embarked", "class"], aggfunc="mean"))

embarked         C         Q         S
sex
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603
``````````````````````````````
embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First
sex
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430

embarked
class       Second     Third
sex
female    0.910448  0.375000
male      0.154639  0.128302
``````````````````````````````
embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First
sex
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430

embarked
class       Second     Third
sex
female    0.910448  0.375000
male      0.154639  0.128302

<ipython-input-22-b51620687c8d>:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  print(df.pivot_table("survived", "sex", ["embarked", "class"]))
<ipython-input-22-b51620687c8d>:7: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  print(df.pivot_table("survived", "sex", ["embarked", "class"], aggfunc="mean"))

In [26]:
# deger siniflandirma yapabilmemizi saglar
df["new_age"] = pd.cut(df["age"], [0,10,18,25,40,90])
df.pivot_table("survived", "sex", "new_age")

# 0,10 arasindaki yaslardan kadinlarin %60 i hayatta kalmis erkeklerin ise %57 si

<ipython-input-26-7521402956ec>:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", "new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
sex
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

In [29]:
pd.set_option("display.width", 200) # ekrana sigmasini saglar
df.pivot_table("survived", "sex", ["new_age", "class"])

<ipython-input-29-34825b28166b>:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", ["new_age", "class"])

new_age (0, 10]                   (10, 18]                   (18, 25]                      (25, 40]                      (40, 90]
class     First Second     Third     First Second     Third     First    Second     Third     First    Second     Third     First    Second     Third
sex
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176  0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154  0.111111
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333  0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238  0.064516

In [30]:
# Apply & Lambda

df["age2"] = df["age"] * 2
df["age3"] = df["age"] * 5

# 10'a bolmek icin

# df["age2"] / 10 yerine

for col in df.columns.values:
    if "age" in col:
        df[col] = df[col] / 10
        print(df[col].head())

# ya da

df[["age", "age2", "age3"]].apply(lambda x: x / 10).head()

# daha sistematik sekilde
df.loc[:, df.columns.str.contains("age")].apply(lambda x: x / 10).head()

    age  survived  pclass     sex  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone  age_new   new_age  age2   age3
0  22.0         0       3    male      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False    484.0  (18, 25]  44.0  110.0
1  38.0         1       1  female      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False   1444.0  (25, 40]  76.0  190.0
2  26.0         1       3  female      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True    676.0  (25, 40]  52.0  130.0
3  35.0         1       1  female      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False   1225.0  (25, 40]  70.0  175.0
4  35.0         0       3    male      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True   1225.0  (25, 40]  70.0  175.0

In [31]:
# Birlestirme Join

import numpy as np

m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df2 = df1 + 99

pd.concat([df1,df2])

# pd.merge(df1, df2, on="employees")

   var1  var2  var3
0    24    23    23
1    22    17    25
2    24     9     9
3    18    19     3
4    20     1    21
0   123   122   122
1   121   116   124
2   123   108   108
3   117   118   102
4   119   100   120